services:
  db:
    image: postgres:16-alpine
    container_name: clientes-db
    environment:
      POSTGRES_USER: clientes_app
      POSTGRES_PASSWORD: dev_password_123
      POSTGRES_DB: clientes
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U clientes_app -d clientes" ]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pgdata:
